@mktsystem_HostAddress = http://localhost:5288
@token = CfDJ8AMzeuekkGdKqENm8PsCSeRqGyIS3xSg8-euiv54XUbsw4wrEYSz-17490bCdY5jEvx-DSEC0fZ-4KdSNocmnn_d8iN3-BvEssi_sjb1p__rMLqueGWqJCdHHsDebJj_hnehncMDl7e8S3JFO8rXXR84_E5Mnc6wJ1Wrrcv3LSO4UBX9zVLuwgNQdql41ylHRlRdzK74XWIZtQ-dM2XbjDn17ZgvkoqutuojoIVwSW5XF50UVvgSKop1XwcGwaEKhKWgRDwbCAiRap4Hbf9rX3Adpu7vHtDFeIlB8WQwxRGbGVNh9D91tBrlCS5Jg_3NfILRJ-L3vO9CjHoREQLFI_JXyL_fuUiU4a_Pet5GQZTcktpqMA7chYVDjRPHTyn3GpZ62qL5x7Kt4a8z3YJCrPIpx3n8MrsoD42zzA5ChoOVPkLkZG3sDg0DIdb_Na_6S_xSwTgKvi7BvYXB1C5B282WSpagcg_9WJj1VP_RBzwSIQtv6lQAfrMLfVvwfwiLOTvNi1vLwu2xUW7iNrF924Ri-_sqHOdx1JhFN3tA9tknhI5Tf9Kf3quX3sg8e-KVoU_eeqfoOEf-LCMkvATtnA-BOmtW5med3Ibsr-XtVFc2GhimU2dxQykXwbguiVo_UKaCrnQaTif-5Bp7_372Emw5rPt7LIfKpjH8J4cIbgni7S8d3vz1Zu8MCIL_oYauBgAdsuhXGtqDXTIuP4nR6qw

### Ahmad
GET {{mktsystem_HostAddress}}/api/payments/970321112345
Accept: application/json


### Aminah
GET {{mktsystem_HostAddress}}/api/payments/980123112345
Accept: application/json



### Ali
GET {{mktsystem_HostAddress}}/api/payments/990945112345
Accept: application/json

### Khalifah
GET {{mktsystem_HostAddress}}/api/payments/190808140373
Accept: application/json

### Creating User Part
POST {{mktsystem_HostAddress}}/register
Content-Type: application/json

{
    "email" : "nuruliftitah@test.com",
    "password" : "Password1!"
}

### Login User Part
POST {{mktsystem_HostAddress}}/login
Content-Type: application/json

{
    "email" : "nuruliftitah@test.com",
    "password" : "Password1!"
}

### Create Attendance
POST {{mktsystem_HostAddress}}/api/attendance/single
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studentId": 1,
  "classId": 1,
  "status": 1
}

### Create Bulk Attendance
POST {{mktsystem_HostAddress}}/api/attendance/bulk
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "classId": 2,
  "date": "2026-04-22T14:42:27.283Z",
  "studentsRequest": [
    {
      "studentId": 2,
      "status": "absent"
    },
    {
      "studentId": 3,
      "status": "absent"
    }
  ]
}


### Excel POST
POST {{mktsystem_HostAddress}}/api/attendance/excel
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="Book1.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./Book1.xlsx
--boundary--


